# golangci-lint 配置文件 for vtool 项目
# 基于 Go 1.23 + 泛型特性
# 兼容 golangci-lint v2

# 运行配置
run:
  go: "1.23"
  concurrency: 4
  timeout: "5m"
  tests: true

# 输出配置
output:
  formats:
    - format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

# Linters 配置
linters-settings:
  errcheck:
    check-type-assertions: true
    check-unchecked: false

  govet:
    enable-all: true
    shadow:
      strict: true

  revive:
    min-confidence: 0.8
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: error-naming
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow
      - unnamedResult
      - unnecessaryDefer
      - builtinShadow

  gocyclo:
    min-complexity: 15

  gofmt:
    check-style: true
    simplify: true

  goimports:
    local-prefixes: "github.com/sword-demon/vtool"

  misspell:
    locale: "US"

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

  dupl:
    threshold: 30

  goconst:
    min-len: 2
    min-occurrences: 5

  mnd:
    settings:
      mnd:
        - "argument"
        - "case"
        - "condition"
        - "return"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "10"
      - "100"
      - "1000"
    ignored-files:
    ignored-functions:

# Linters 配置
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - mnd
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - depguard
    - gochecknoglobals
    - err113

# 问题和警告
issues:
  exclude-rules:
    # 测试文件中的问题
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - goconst
        - gocyclo
        - mnd
        - govet
        - lll
        - misspell
        - revive
        - stylecheck
        - unparam
        - whitespace
        - dupl
        - gocritic

    # 外部包装器文件允许内部包导入
    - path: ^(bean|list|mapx|queue|sets|slice)/
      linters:
        - revive
        - gocritic
      text: ""

    # 忽略特定问题
    - linters:
        - gocritic
      text: "duplicateImport"

    # 忽略某些特定文件的问题
    - path: internal/bean/copier\.go
      linters:
        - gocritic
      text: "unslice"

    # 忽略 rand 问题（用于跳表）
    - path: internal/list/skiplist\.go
      linters:
        - gosec
      text: "G404"

    # 忽略 errcheck 在特定方法中的问题
    - path: internal/list/arraylist\.go
      linters:
        - errcheck
      text: "Error return value"

    - path: internal/list/linkedlist\.go
      linters:
        - errcheck
      text: "Error return value"

    # 忽略 errcheck 在类型断言中的问题
    - path: internal/bean/copier\.go
      linters:
        - errcheck
      text: "Error return value is not checked"

    # 忽略 gosec 整数溢出（类型转换）
    - path: internal/bean/copier\.go
      linters:
        - gosec
      text: "G115"

    # 忽略 mnd 魔数检查（在某些情况下）
    - path: internal/list/arraylist\.go
      linters:
        - mnd
      text: "Magic number"

    # 忽略 dupl 重复代码（在测试和某些合理场景）
    - path: internal/mapx/linkedmap\.go
      linters:
        - dupl
      text: "lines are duplicate"

    - path: internal/mapx/treemap\.go
      linters:
        - dupl
      text: "lines are duplicate"

    - path: internal/set/sortedset\.go
      linters:
        - dupl
      text: "lines are duplicate"

    - path: internal/bean/copier\.go
      linters:
        - dupl
      text: "lines are duplicate"

    - path: internal/list/skiplist\.go
      linters:
        - dupl
      text: "lines are duplicate"

    # 忽略 depguard 问题（暂时禁用 depguard）
    - path: .*
      linters:
        - depguard
      text: "import"

  exclude:
    - "comment on exported"
    - "ineffassign"

  exclude-paths:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - ".*_test\\.go$"
    - vendor
    - .git
    - .idea
    - .vscode
    - node_modules
    - dist
    - build

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

# 性能优化
performance:
  pre-analyze-go-version: "1.23"